---
    - name: Update APT package cache 
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist 
        
    - name: Install Apache Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache', 'php', 'libapache2-mod-php', 'php-mysql', 'php-curl', 'php-json' ]

    - name: Create document root
      file:
        path: "/var/www/{{ apache_document_root }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Set up Apache virtualhost
      template:
        src: "apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf_name }}"

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf_name }}
      notify: Reload Apache

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted