---
    - name: installation of LAMP-STACK packages, and their dependencies
      become: yes
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - httpd
        - mysql
        - php
        - php-json
        - php-curl
        - php-mysqlnd
        - php-fpm
        - php-opcache
        - php-gd
        
    - name: Setsebool
      become: yes
      command: setsebool -P httpd_execmem 1

    - name: Disabling the default welcoming page
      become: yes
      command: mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf_backup

    - name: Setsebool
      become: yes
      command: setenforce 0

    - name: Enable the httpd service
      become: yes
      systemd:
        name: httpd
        enabled: yes
      notify:
        - Start httpd

    - name: Start the httpd service
      become: yes
      systemd:
        name: httpd
        state: started
      ignore_errors: yes 
