---
    - name: Update APT package cache
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade all packages
      become: yes
      apt:
        upgrade: dist 
        
    - name: Install Packages for apache load balancing
      become: yes
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'libxml2-dev' ]

    - name: Enable the rewrite module
      become: yes
      ansible.builtin.command: a2enmod rewrite

    - name: Enable the proxy module
      become: yes
      ansible.builtin.command: a2enmod proxy

    - name: Enable the proxy_balancer module
      become: yes
      ansible.builtin.command: a2enmod proxy_balancer

    - name: Enable the proxy_http module
      become: yes
      ansible.builtin.command: a2enmod proxy_http

    - name: Enable the headers module
      become: yes
      ansible.builtin.command: a2enmod headers

    - name: Enable the lbmethod_bytraffic module
      become: yes
      ansible.builtin.command: a2enmod lbmethod_bytraffic

    - name: Set up Apache load-balancer configuration
      become: yes
      template:
        src: "lb_config.j2"
        dest: "/etc/apache2/sites-available/000-default.conf"

  handlers:
    - name: Reload Apache
      become: yes
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      become: yes
      service:
        name: apache2
        state: restarted











