---
    - name: Create document root on webserver
      become: yes
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        owner: apache
        mode: 0755
        
    - name: install nfs-utils
      become: yes
      package: 
        name: nfs-utils
        state: latest

    - name: nfs4-acl-tools
      become: yes
      package: 
        name: nfs4-acl-tools
        state: latest

    - name: Mount volumn on document root
      become: yes
      shell: mount -t nfs -o rw,nosuid {{ nfs_ip }}:{{ nsf_server_mounted_point }} {{ nsf_client_mount_dir }}

  handlers:
    - name: Reload nsf-server
      become: yes
      service:
        name: nsf-server
        state: reloaded

    - name: Restart nsf-server
      become: yes
      service:
        name: nsf-server
        state: restarted