---
- name: Setting up NFS server
  hosts: nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  vars_files:
    - vars/default.yml
  tasks:
    - name: partioning disk 1
      parted:
        device: /dev/xvdf
        number: 1
        flags: [ lvm ]
        state: present
        part_start: 0%
        part_end: 100%

    - name: partioning disk 2
      parted:
        device: /dev/xvdg
        number: 1
        flags: [ lvm ]
        state: present
        part_start: 0%
        part_end: 100%

    - name: partioning disk 3
      parted:
        device: /dev/xvdh
        number: 1
        flags: [ lvm ]
        state: present
        part_start: 0%
        part_end: 100%

    - name: Install lvm2 dependency
      yum: name=lvm2 state=latest

    - name: Creating PV for disk
      command: sudo pvcreate /dev/xvdf1 /dev/xvdg1 /dev/xvdh1

    - name: Creating VG for the disk 
      command: sudo vgcreate "{{ vg_name }}" /dev/xvdf1 /dev/xvdg1 /dev/xvdh1 

    - name: Creating first logical volume
      lvol:
         vg: "{{ vg_name }}"
         lv: "{{ lv_1 }}"
         size: "{{ lv_1_size }}"
         force: yes

    - name: Creating second logical volume
      lvol:
        vg: "{{ vg_name }}"
         lv: "{{ lv_2 }}"
         size: "{{ lv_2_size }}"
         force: yes

    - name: Creating mount directory inside Parent
      ansible.builtin.file:
        path: /mnt/apps
        state: directory
        owner: nobody
        mode: 0755

    - name: Creating mount directory inside Parent
      ansible.builtin.file:
       path: /mnt/logs
       state: directory
       owner: nobody
       mode: 0755

    - name: Formating first LV
      filesystem: 
        fstype: xfs
        dev: "/dev/{{ vg_name }}/{{ lv_1 }}"

    - name: Formating second LV
      filesystem: 
        fstype: xfs
        dev: "/dev/{{ vg_name }}/{{ lv_2 }}"

    - name: mounting first lv
      mount:
        path: /mnt/apps
        src: "/dev/{{ vg_name }}/{{ lv_1 }}"
        fstype: xfs
        state: mounted

    - name: mounting second lv
      mount:
        path: /mnt/logs
        src: "/dev/{{ vg_name }}/{{ lv_2 }}"
        fstype: xfs
        state: mounted

    - name: installing nfs utilit
      package:
          name: nfs-utils
          state: latest 

    - name: Copy exports file.
      template:
        src: ./files/exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644

    - name: NFS apply change configrue
      shell: systemctl reload nfs;exportfs -a

    - name: enable rpcbind nfslock nfs
      service:
        name: "{{ item }}"
        enabled: yes
      with_items:
        - rpcbind
        - nsf-server.service

    - name: enable rpcbind nfslock nfs
      service:
        name: "{{ item }}"
        started: yes
      with_items:
        - nsf-server.service

- name: Setting up NFS client and httpd webservers
  hosts: webservers
  remote_user: ec2-user
  become: yes
  become_user: root
  vars_files:
    - vars/default.yml
  tasks:
    - name: Create document root on webserver
      ansible.builtin.file:
          path: /var/www/html
          state: directory
          owner: apache
          mode: 0755
        
    - name: install nfs-utils
      package: 
          name: nfs-utils
          state: latest
    - name: install nfs-utils
      package: 
          name: nfs4-acl-tools
          state: latest

    - name: Mount volumn on document root
      shell: sudo mount -t nfs -o rw,nosuid {{ nfs_ip }}:/mnt/apps /var/www/html

  #implementation of webserver
    - name: installation of LAMP-STACK packages, and their dependencies
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - httpd
        - mysql
        - php
        - php-json
        - php-curl
        - php-mysqlnd
        - php-fpm
        - php-opcache
        - php-gd
        
    - name: Copy index test page
      template:
        src: "files/index.html.j2"
        dest: "/var/www/html/index.html"
        
    - name: Setsebool
      command: setsebool -P httpd_execmem 1

    - name: Disabling the default welcoming page
      command: sudo mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf_backup
      command: sudo setenforce 0

    - name: Enable the httpd service
      systemd:
        name: httpd
        enabled: yes
      notify:
        - Start httpd

    - name: Start the httpd service
      systemd:
        name: httpd
        state: started
      ignore_errors: yes 
# End of webserver
