---
- hosts: NFS-Server-Set-Up
  remote_user: ec2-user
  become: yes
  become_user: root
  vars_files:
    - vars/default.yml
  tasks:
    - name: 
    - name: partioning disk 1
      parted:
        device: /dev/xvdf
        number: 1
        flags: [ lvm ]
        state: present
        part_start: 0%
        part_end: 100%

    - name: partioning disk 2
      parted:
        device: /dev/xvdg
        number: 1
        flags: [ lvm ]
        state: present
        part_start: 0%
        part_end: 100%

    - name: partioning disk 3
      parted:
        device: /dev/xvdh
        number: 1
        flags: [ lvm ]
        state: present
        part_start: 0%
        part_end: 100%

    - name: Install lvm2 dependency
        package:
          name: lvm2
          state: latest

    - name: Creating PV for disk 1
      lvg:
         pv: /dev/xvdf1
         vg: "{{ vg_name }}"

    - name: Creating PV for disk 2
      lvg:
          pv: /dev/xvdg1
          vg: "{{ vg_name }}"

    - name: Creating PV for disk 3
      lvg:
          pv: /dev/xvdh1
          vg: "{{ vg_name }}"

    - name: Creating first logical volume
      lvol:
          vg: "{{ vg_name }}"
          lv: "{{ lv_1 }}"
          size: "{{ lv_1_size }}"
          force: yes

    - name: Creating second logical volume
      lvol:
          vg: "{{ vg_name }}"
          lv: "{{ lv_2 }}"
          size: "{{ lv_2_size }}"
          force: yes

    - name: Creating mount directory inside Parent
      ansible.builtin.file:
        path: /mnt/apps
        state: directory
        mode: 0755
 
    - name: Creating mount directory inside Parent
      ansible.builtin.file:
        path: /mnt/logs
        state: directory
        mode: 0755

    -name: Formating first LV
      filesystem: 
        fstype: xfs
        dev: /dev/"{{ vg_name }}"/"{{ lv_1_size }}"

    -name: Formating second LV
      filesystem: 
        fstype: xfs
        dev: /dev/"{{ vg_name }}"/"{{ lv_2_size }}"

    -name: mounting first lv
      mount:
        path: /mnt/apps
        src: /dev/"{{ vg_name }}"/"{{ lv_1_size }}"
        fstype: xfs
        state: mounted

    -name: mounting second lv
      mount:  /mnt/logs
        src: /dev/"{{ vg_name }}"/"{{ lv_2_size }}"
        stype: xfs
        tate: mounted

    - name: Network_File_System (NFS) Server Set Up
        package:
          name: nfs-utils
          state: latest 

    - name: enable rpcbind nfslock nfs
      service:
        name: "{{ item }}"
        enabled: yes
      with_items:
        - rpcbind
        - nfslock
        - nfs

    - name: Copy exports file.
      template:
        src: ./filesexports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644

    - name: NFS apply change configrue
      shell: systemctl reload nfs;exportfs -a

- hosts: webservers
  remote_user: ec2-user
  become: yes
  become_user: root
  vars_files:
    - vars/default.yml
  tasks:
    - name: Create document root on webserver
        ansible.builtin.file:
          path: /var/www/{{ domain_name }}
          state: directory
          owner: root
          mode: 0755
        
    - name: install nfs-utils
        package: 
          name: nfs-utils
          state: latest

    - name: Mount volumn on document root
        shell: sudo mount {{ nfs_ip }}:/home/vagrant/nfs_test /mnt/apps