---
- name: Setting up NFS client and httpd webservers
  hosts: webservers
  remote_user: ec2-user
  become: yes
  become_user: root
  vars_files:
    - ../vars/default.yml
  tasks:
    - name: installation of LAMP-STACK packages, and their dependencies
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - httpd
        - mysql
        - php
        - php-json
        - php-curl
        - php-mysqlnd
        - php-fpm
        - php-opcache
        - php-gd
        
    - name: Copy index test page
      template:
        src: "files/index.html.j2"
        dest: "/var/www/html/index.html"
        
    - name: Setsebool
      command: setsebool -P httpd_execmem 1

    - name: Disabling the default welcoming page
      command: sudo mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf_backup
      command: sudo setenforce 0

    - name: Enable the httpd service
      systemd:
        name: httpd
        enabled: yes
      notify:
        - Start httpd

    - name: Start the httpd service
      systemd:
        name: httpd
        state: started
      ignore_errors: yes 
# End of webserver
